package classes

import "github.com/sparkymat/webdsl/css"

const Container css.Class = "container"
const ContainerFluid css.Class = "container-fluid"
const Row css.Class = "row"
const NoGutters css.Class = "no-gutters"
const ClearFix css.Class = "clearfix"

const FlexUnordered css.Class = "flex-unordered"
const FlexFirst css.Class = "flex-first"
const FlexLast css.Class = "flex-last"

const AlignItemsStart css.Class = "align-items-start"
const AlignItemsCenter css.Class = "align-items-center"
const AlignItemsEnd css.Class = "align-items-end"

const AlignSelfStart css.Class = "align-self-start"
const AlignSelfCenter css.Class = "align-self-center"
const AlignSelfEnd css.Class = "align-self-end"

const JustifyContentStart css.Class = "justify-content-start"
const JustifyContentCenter css.Class = "justify-content-center"
const JustifyContentEnd css.Class = "justify-content-end"
const JustifyContentAround css.Class = "justify-content-around"
const JustifyContentBetween css.Class = "justify-content-between"

const Col css.Class = "col"

const Col1 css.Class = "col-1"
const Col2 css.Class = "col-2"
const Col3 css.Class = "col-3"
const Col4 css.Class = "col-4"
const Col5 css.Class = "col-5"
const Col6 css.Class = "col-6"
const Col7 css.Class = "col-7"
const Col8 css.Class = "col-8"
const Col9 css.Class = "col-9"
const Col10 css.Class = "col-10"
const Col11 css.Class = "col-11"
const Col12 css.Class = "col-12"

const Offset1 css.Class = "offset-1"
const Offset2 css.Class = "offset-2"
const Offset3 css.Class = "offset-3"
const Offset4 css.Class = "offset-4"
const Offset5 css.Class = "offset-5"
const Offset6 css.Class = "offset-6"
const Offset7 css.Class = "offset-7"
const Offset8 css.Class = "offset-8"
const Offset9 css.Class = "offset-9"
const Offset10 css.Class = "offset-10"
const Offset11 css.Class = "offset-11"
const Offset12 css.Class = "offset-12"

const ColSm1 css.Class = "col-sm-1"
const ColSm2 css.Class = "col-sm-2"
const ColSm3 css.Class = "col-sm-3"
const ColSm4 css.Class = "col-sm-4"
const ColSm5 css.Class = "col-sm-5"
const ColSm6 css.Class = "col-sm-6"
const ColSm7 css.Class = "col-sm-7"
const ColSm8 css.Class = "col-sm-8"
const ColSm9 css.Class = "col-sm-9"
const ColSm10 css.Class = "col-sm-10"
const ColSm11 css.Class = "col-sm-11"
const ColSm12 css.Class = "col-sm-12"

const OffsetSm1 css.Class = "offset-sm-1"
const OffsetSm2 css.Class = "offset-sm-2"
const OffsetSm3 css.Class = "offset-sm-3"
const OffsetSm4 css.Class = "offset-sm-4"
const OffsetSm5 css.Class = "offset-sm-5"
const OffsetSm6 css.Class = "offset-sm-6"
const OffsetSm7 css.Class = "offset-sm-7"
const OffsetSm8 css.Class = "offset-sm-8"
const OffsetSm9 css.Class = "offset-sm-9"
const OffsetSm10 css.Class = "offset-sm-10"
const OffsetSm11 css.Class = "offset-sm-11"
const OffsetSm12 css.Class = "offset-sm-12"

const ColMd1 css.Class = "col-md-1"
const ColMd2 css.Class = "col-md-2"
const ColMd3 css.Class = "col-md-3"
const ColMd4 css.Class = "col-md-4"
const ColMd5 css.Class = "col-md-5"
const ColMd6 css.Class = "col-md-6"
const ColMd7 css.Class = "col-md-7"
const ColMd8 css.Class = "col-md-8"
const ColMd9 css.Class = "col-md-9"
const ColMd10 css.Class = "col-md-10"
const ColMd11 css.Class = "col-md-11"
const ColMd12 css.Class = "col-md-12"

const OffsetMd1 css.Class = "offset-md-1"
const OffsetMd2 css.Class = "offset-md-2"
const OffsetMd3 css.Class = "offset-md-3"
const OffsetMd4 css.Class = "offset-md-4"
const OffsetMd5 css.Class = "offset-md-5"
const OffsetMd6 css.Class = "offset-md-6"
const OffsetMd7 css.Class = "offset-md-7"
const OffsetMd8 css.Class = "offset-md-8"
const OffsetMd9 css.Class = "offset-md-9"
const OffsetMd10 css.Class = "offset-md-10"
const OffsetMd11 css.Class = "offset-md-11"
const OffsetMd12 css.Class = "offset-md-12"

const ColLg1 css.Class = "col-lg-1"
const ColLg2 css.Class = "col-lg-2"
const ColLg3 css.Class = "col-lg-3"
const ColLg4 css.Class = "col-lg-4"
const ColLg5 css.Class = "col-lg-5"
const ColLg6 css.Class = "col-lg-6"
const ColLg7 css.Class = "col-lg-7"
const ColLg8 css.Class = "col-lg-8"
const ColLg9 css.Class = "col-lg-9"
const ColLg10 css.Class = "col-lg-10"
const ColLg11 css.Class = "col-lg-11"
const ColLg12 css.Class = "col-lg-12"

const OffsetLg1 css.Class = "offset-lg-1"
const OffsetLg2 css.Class = "offset-lg-2"
const OffsetLg3 css.Class = "offset-lg-3"
const OffsetLg4 css.Class = "offset-lg-4"
const OffsetLg5 css.Class = "offset-lg-5"
const OffsetLg6 css.Class = "offset-lg-6"
const OffsetLg7 css.Class = "offset-lg-7"
const OffsetLg8 css.Class = "offset-lg-8"
const OffsetLg9 css.Class = "offset-lg-9"
const OffsetLg10 css.Class = "offset-lg-10"
const OffsetLg11 css.Class = "offset-lg-11"
const OffsetLg12 css.Class = "offset-lg-12"

const ColXl1 css.Class = "col-xl-1"
const ColXl2 css.Class = "col-xl-2"
const ColXl3 css.Class = "col-xl-3"
const ColXl4 css.Class = "col-xl-4"
const ColXl5 css.Class = "col-xl-5"
const ColXl6 css.Class = "col-xl-6"
const ColXl7 css.Class = "col-xl-7"
const ColXl8 css.Class = "col-xl-8"
const ColXl9 css.Class = "col-xl-9"
const ColXl10 css.Class = "col-xl-10"
const ColXl11 css.Class = "col-xl-11"
const ColXl12 css.Class = "col-xl-12"

const OffsetXl1 css.Class = "offset-xl-1"
const OffsetXl2 css.Class = "offset-xl-2"
const OffsetXl3 css.Class = "offset-xl-3"
const OffsetXl4 css.Class = "offset-xl-4"
const OffsetXl5 css.Class = "offset-xl-5"
const OffsetXl6 css.Class = "offset-xl-6"
const OffsetXl7 css.Class = "offset-xl-7"
const OffsetXl8 css.Class = "offset-xl-8"
const OffsetXl9 css.Class = "offset-xl-9"
const OffsetXl10 css.Class = "offset-xl-10"
const OffsetXl11 css.Class = "offset-xl-11"
const OffsetXl12 css.Class = "offset-xl-12"
